<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Confiz-4343" failures="1" tests="14" name="Complete test run" time="20.559" errors="0" timestamp="2022-03-18T15:53:21 PKT">
  <testcase classname="rdm.CreateNewUserAPI" name="addNewUserAPI" time="2.979"/>
  <testcase classname="rdm.CreateNewUserAPI" name="addNewUserAPI" time="1.344"/>
  <testcase classname="rdm.CreateNewUserAPI" name="addNewUserAPI" time="1.53"/>
  <testcase classname="rdm.CreateNewUserAPI" name="addNewUserAPI" time="1.35"/>
  <testcase classname="rdm.CreateNewUserAPI" name="addNewUserAPI" time="1.214"/>
  <testcase classname="rdm.GetSingleUserAPI" name="GetsingleUserAPI" time="0.871"/>
  <testcase classname="rdm.GetSingleUserAPI" name="GetsingleUserAPI" time="0.936"/>
  <testcase classname="rdm.GetSingleUserAPI" name="GetsingleUserAPI" time="0.838"/>
  <testcase classname="rdm.GetSingleUserAPI" name="GetsingleUserAPI" time="0.913"/>
  <testcase classname="rdm.GetSingleUserAPI" name="GetsingleUserAPI" time="1.538">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:819)
at org.testng.Assert.assertEquals(Assert.java:829)
at rdm.GetSingleUserAPI.GetsingleUserAPI(GetSingleUserAPI.java:40)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:418)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
]]>
    </failure>
  </testcase> <!-- GetsingleUserAPI -->
  <testcase classname="rdm.UpdateRecordAPI" name="UpdateUserRecordAPI" time="1.235"/>
  <testcase classname="rdm.UpdateRecordAPI" name="UpdateUserRecordAPI" time="1.79"/>
  <testcase classname="rdm.DeleteRecordAPI" name="DeleteUser" time="1.214"/>
  <testcase classname="rdm.DeleteRecordAPI" name="DeleteUser" time="1.326"/>
</testsuite> <!-- Complete test run -->
